'use strict';
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const H=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('cm$'+s)))].map(b=>b.toString(16).padStart(2,'0')).join('');
// ---- SF Symbols-style inline icons (24px grid, 1.75 stroke, round caps) ----
const P={home:'<path d="M4 10.5 12 4l8 6.5V20H4z"/><path d="M10 20v-6h4v6"/>',book:'<path d="M5 4h11a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3z"/><path d="M5 17a3 3 0 0 1 3-3h11"/>',users:'<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20c.5-3.5 3-5.5 6.5-5.5s6 2 6.5 5.5"/><path d="M16 4.7a3.5 3.5 0 0 1 0 6.6M18 14.8c2 .6 3.300 2.4 3.5 5.2"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4.5 20c.6-4 3.5-6 7.5-6s6.900 2 7.5 6"/>',userplus:'<circle cx="10" cy="8" r="3.5"/><path d="M3 20c.6-3.8 3.2-5.8 7-5.8"/><path d="M18 13v6M15 16h6"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="M5 12.5 10 17.5 19 7"/>',clock:'<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>',alert:'<path d="M12 4 21 19H3z"/><path d="M12 10v4M12 16.8v.2"/>',chart:'<path d="M5 20v-7M12 20V5M19 20V10"/>',bell:'<path d="M6 16v-5a6 6 0 0 1 12 0v5l1.5 2h-15z"/><path d="M10 21h4"/>',trash:'<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v6M14 11v6"/>',archive:'<rect x="3" y="4" width="18" height="5" rx="1.5"/><path d="M5 9v10h14V9M10 13h4"/>',download:'<path d="M12 4v11M7.5 11 12 15.5 16.5 11M5 20h14"/>',calendar:'<rect x="3.5" y="5" width="17" height="15" rx="3"/><path d="M3.5 10h17M8 3v4M16 3v4"/>',megaphone:'<path d="M4 10v4h3l8 4V6L7 10z"/><path d="M19 9.5a4 4 0 0 1 0 5"/>',file:'<path d="M7 3h7l5 5v12a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/><path d="M14 3v5h5"/>',edit:'<path d="M4 20h4L19 9l-4-4L4 16z"/><path d="m13.5 6.5 4 4"/>',key:'<circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M16 7l3 3"/>',moon:'<path d="M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5z"/>',logout:'<path d="M10 4H5v16h5M15 8l4 4-4 4M19 12H9"/>',inbox:'<path d="M3.5 13 6 5h12l2.5 8v6h-17z"/><path d="M3.5 13H9a3 3 0 0 0 6 0h5.5"/>',send:'<path d="M20 4 10 14M20 4l-6 16-4-6-6-4z"/>',star:'<path d="m12 4 2.5 5 5.5.8-4 3.900.9 5.5-4.900-2.6L7.100 19.2 8 13.7 4 9.8 9.5 9z"/>',cap:'<path d="M2.5 9 12 4.5 21.5 9 12 13.5z"/><path d="M6.5 11.5V16c0 1.5 2.5 3 5.5 3s5.5-1.5 5.5-3v-4.5M21.5 9v6"/>',lock:'<rect x="5" y="11" width="14" height="9" rx="2.5"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',x:'<path d="M6 6l12 12M18 6 6 18"/>',dot:'<circle cx="12" cy="12" r="3.5" fill="currentColor"/>'};
const I=(n,z=18)=>`<svg class="ic" width="${z}" height="${z}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${P[n]||''}</svg>`;
const BI=[['New classroom','plus'],['Add student','userplus'],['Add module','plus'],['Add material','plus'],['New assignment','plus'],['Post announcement','megaphone'],['Add note','edit'],['Submit work','send'],['Save','check'],['Cancel','x'],['Done','check'],['Copy','file'],['Remove','trash'],['Delete','trash'],['Unarchive','archive'],['Archive','archive'],['Update','edit'],['Open board','star'],['Edit grade','edit'],['Grade','star'],['Export','download'],['Reset password','key'],['Issue new','key'],['Deactivate','lock'],['Reactivate','lock'],['Theme','moon'],['Sign out','logout'],['Sign in','user'],['Request reset','send'],['Back','x'],['Roster','users'],['Content','book'],['Assignments','file'],['Attendance','calendar'],['Announcements','megaphone'],['Instructor','cap'],['Student','user']];
const NI={'#/':'home','#/classes':'book','#/students':'users','#/progress':'chart','#/notifs':'bell','#/profile':'user'},BD={absent:'x',excused:'clock',submitted:'check',graded:'check',present:'check',late:'clock',pending:'clock',missing:'alert',inactive:'lock',archived:'archive',shared:'users',private:'lock',new:'dot'};
function deco(r){r.querySelectorAll('button,a.btn').forEach(b=>{if(b.dataset.d)return;b.dataset.d=1;const t=b.textContent.trim(),m=BI.find(([k])=>t.startsWith(k));if(m)b.insertAdjacentHTML('afterbegin',I(m[1],b.classList.contains('s')?15:18))});
 r.querySelectorAll('nav.side a.nl').forEach(a=>a.insertAdjacentHTML('afterbegin',I(NI[a.getAttribute('href')]||'dot',20)));
 r.querySelectorAll('.b').forEach(b=>{if(b.querySelector('svg'))return;const k=b.getAttribute('role')=='alert'?'alert':BD[b.textContent.trim().split(' ').pop().toLowerCase()];if(k)b.insertAdjacentHTML('afterbegin',I(k,13))});
 r.querySelectorAll('.empty').forEach(e=>e.insertAdjacentHTML('afterbegin',I('inbox',24)));
 r.querySelectorAll('.brand i').forEach(i=>i.outerHTML='<span class="logo">'+I('cap',18)+'</span>')}
const uid=()=>Math.random().toString(36).slice(2,9),DAY=864e5,now=()=>Date.now();
const tmp=()=>{const a=new Uint32Array(2);crypto.getRandomValues(a);return 'Tmp-'+[...a].map(n=>n.toString(36)).join('').slice(0,8)+'!'};
let DB,ME,tab='roster',authRole='instructor',authMsg='';const fd=d=>new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric'}),dstr=t=>new Date(t).toISOString().slice(0,10);
const save=()=>localStorage.setItem('cm_db',JSON.stringify(DB));
const toast=m=>{const t=$('#toast');t.textContent=m;t.className='on';clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='',2600)};
const log=t=>{DB.log.unshift({t,at:now()});DB.log.length=Math.min(DB.log.length,40)};
const ntf=(u,t)=>DB.notifs.unshift({id:uid(),u,t,at:now(),r:0});
async function seed(){const P=await H('Learn123!'),T=await H('Teach123!'),n=now(),U=[{id:'i1',role:'instructor',name:'Dr. Maya Rao',email:'instructor@demo.edu',pw:T,must:0,on:1}];
 ['Ava Chen','Ben Okafor','Chloe Martin','Dev Patel','Emma Silva','Farid Nasser'].forEach((x,i)=>U.push({id:'s'+i,role:'student',name:x,email:x.split(' ')[0].toLowerCase()+'@demo.edu',pw:P,must:0,on:1}));
 const C=[{id:'c1',name:'Biology 101',code:'BIO-101',arch:0,st:['s0','s1','s2','s3','s4'],mods:[{t:'Module 1: Cells',items:[{t:'Cell structure (PDF)',u:'https://example.com/cells.pdf',v:2},{t:'Intro video',u:'https://example.com/v',v:1}]}]},{id:'c2',name:'World History',code:'HIS-210',arch:0,st:['s0','s2','s4','s5'],mods:[{t:'Module 1: Ancient Rome',items:[{t:'Reading list',u:'https://example.com/rome',v:1}]}]}];
 const A=[{id:'a1',cid:'c1',t:'Cell diagram lab',d:'Label and annotate a plant cell.',due:n-5*DAY,max:50},{id:'a2',cid:'c1',t:'Photosynthesis quiz',d:'Short written answers.',due:n+4*DAY,max:30},{id:'a3',cid:'c2',t:'Essay: Fall of Rome',d:'800 words.',due:n-2*DAY,max:100},{id:'a4',cid:'c2',t:'Map exercise',d:'Trade routes.',due:n+7*DAY,max:20}];
 const S=[];[['a1','s0',46],['a1','s1',38],['a1','s2',22],['a1','s3',0,1],['a3','s0',88],['a3','s2',54],['a3','s4',0,1]].forEach(([a,s,sc,late])=>S.push({id:uid(),aid:a,sid:s,text:'Submitted work.',at:late?n-1*DAY:n-6*DAY,sc:late?null:sc,fb:late?'':'Good effort.'}));
 const AT=[];C.forEach(c=>{for(let d=1;d<=14;d++){const t=dstr(n-d*DAY);c.st.forEach((s,i)=>AT.push({cid:c.id,d:t,s,v:(d*7+i*3+c.id.length)%11==0?'A':(d*5+i)%9==0?'L':'P'}))}});
 return{users:U,classes:C,assigns:A,subs:S,att:AT,anns:[{id:uid(),cid:'c1',t:'Lab safety goggles are required Friday.',at:n-DAY}],notes:[],notifs:[],resets:[],log:[{t:'Ben Okafor submitted Cell diagram lab',at:n-5*DAY},{t:'Announcement posted in Biology 101',at:n-DAY}]}}
const U=id=>DB.users.find(u=>u.id==id),C_=id=>DB.classes.find(c=>c.id==id);
const mine=()=>ME.role=='instructor'?DB.classes:DB.classes.filter(c=>c.st.includes(ME.id)&&!c.arch);
const sub=(a,s)=>DB.subs.find(x=>x.aid==a&&x.sid==s);
const stat=(a,s)=>{const x=sub(a.id,s);return x?(x.sc!=null?'graded':x.at>a.due?'late':'submitted'):(now()>a.due?'missing':'pending')};
const BC={present:'ok',absent:'bad',excused:'n',graded:'ok',submitted:'ok',late:'bad',missing:'bad',pending:'warn'};const badge=s=>`<span class="b ${BC[s]}">${s}</span>`;
const avg=(s,c)=>{const g=DB.assigns.filter(a=>a.cid==c).map(a=>[a,sub(a.id,s)]).filter(([a,x])=>x&&x.sc!=null);return g.length?Math.round(g.reduce((t,[a,x])=>t+x.sc/a.max,0)/g.length*100):null};
const attP=(s,c)=>{const r=DB.att.filter(a=>a.s==s&&(!c||a.cid==c));return r.length?Math.round(r.filter(a=>a.v=='P'||a.v=='E').length/r.length*100):null};
const comp=(s,c)=>{const A=DB.assigns.filter(a=>a.cid==c);return A.length?Math.round(A.filter(a=>sub(a.id,s)).length/A.length*100):0};
const ring=(p,l)=>`<svg width="96" height="96" viewBox="0 0 36 36" role="img" aria-label="${l} ${p}%"><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--line)" stroke-width="3.5"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--pri)" stroke-width="3.5" stroke-linecap="round" stroke-dasharray="${p} 100" transform="rotate(-90 18 18)"/><text x="18" y="21" text-anchor="middle" font-size="8" font-weight="700" fill="var(--ink)">${p}%</text></svg>`;
const bars=(d)=>`<div role="img" aria-label="Bar chart" style="display:flex;gap:14px;align-items:flex-end;height:140px">${d.map(([l,v])=>`<div style="flex:1;text-align:center"><div style="height:${Math.max(v||0,3)}px;background:var(--pri);border-radius:8px 8px 0 0;transition:height .6s"></div><small>${E(l)}<br><b>${v??'–'}%</b></small></div>`).join('')}</div>`;
const heat=(s,c)=>{const r=DB.att.filter(a=>a.s==s&&a.cid==c).sort((a,b)=>a.d<b.d?-1:1).slice(-14);return`<div class="hm" aria-label="Attendance heatmap">${r.map(a=>`<i title="${a.d}: ${a.v}" style="background:${a.v=='P'?'var(--ok)':a.v=='L'?'var(--warn)':a.v=='E'?'var(--pri)':'var(--bad)'}"></i>`).join('')}</div>`};
// modal
function modal(title,html,cb){$('#modal').innerHTML=`<div class="dlg" role="dialog" aria-modal="true" aria-label="${E(title)}"><h2>${E(title)}</h2><form id="mf">${html}<div class="row" style="margin-top:16px"><button class="btn p">Save</button><button type="button" class="btn" onclick="closeM()">Cancel</button></div></form></div>`;const f=$('#mf');deco($('#modal'));(f.querySelector('input,select,textarea')||f).focus?.();f.onsubmit=async e=>{e.preventDefault();if(await cb(Object.fromEntries(new FormData(f)))!==false)closeM()}}
const closeM=()=>$('#modal').innerHTML='';document.addEventListener('keydown',e=>e.key=='Escape'&&closeM());
const confirmM=(msg,fn)=>modal('Please confirm',`<p>${E(msg)}</p>`,fn);
const field=(l,n,t='text',v='',x='')=>`<label for="f_${n}">${l}</label><input id="f_${n}" name="${n}" type="${t}" value="${E(v)}" ${x}>`;
// auth
async function login(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),u=DB.users.find(x=>x.email==f.email.trim().toLowerCase()&&x.role==authRole);
 if(!u||u.pw!=await H(f.pw)||!u.on){authMsg='Email or password is incorrect for the '+authRole+' login.';return render()}
 ME=u;sessionStorage.setItem('cm_me',u.id);location.hash='#/';render()}
const logout=()=>{sessionStorage.removeItem('cm_me');ME=null;render()};
function authView(){const f=authMsg==='forgot';return`<div class="auth"><div class="card"><div class="brand"><i></i>Classroom</div>
<div class="tabs" role="tablist">${['instructor','student'].map(r=>`<button role="tab" aria-selected="${authRole==r}" onclick="authRole='${r}';authMsg='';render()">${r[0].toUpperCase()+r.slice(1)}</button>`).join('')}</div>
${f?`<h1>Reset password</h1><form onsubmit="forgot(event)">${field('Email','email','email')}${authRole=='instructor'?field('New password (min 8)','np','password','','minlength=8 required'):'<p class="mut">Your instructor will be notified and will issue a new temporary password.</p>'}<div class="row" style="margin-top:14px"><button class="btn p">${authRole=='student'?'Request reset':'Reset password'}</button><button type="button" class="btn" onclick="authMsg='';render()">Back</button></div></form>`:
`<h1>${authRole=='instructor'?'Instructor':'Student'} sign in</h1>${authMsg?`<p role="alert" class="b bad">${E(authMsg)}</p>`:''}<form onsubmit="login(event)">${field('Email','email','email','','required autocomplete=username')}${field('Password','pw','password','','required autocomplete=current-password')}<div class="row sp" style="margin-top:14px"><button class="btn p">Sign in</button><a href="#" onclick="authMsg='forgot';render();return false">Forgot password?</a></div></form>
<p class="mut" style="margin-top:16px;font-size:13px">Demo: instructor@demo.edu / Teach123! · ananya@demo.edu / Learn123!<br>Google sign-in needs a backend OAuth client; see README.</p>`}</div></div>`}
async function forgot(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),u=DB.users.find(x=>x.email==f.email.trim().toLowerCase()&&x.role==authRole);
 if(u&&authRole=='student'){DB.resets.push({sid:u.id,at:now()});ntf('i1',u.name+' requested a password reset');log(u.name+' requested a password reset')}
 else if(u){u.pw=await H(f.np);u.must=0}save();authMsg='';render();toast('If the account exists, the reset was processed.')}
function forceView(){return`<div class="auth"><div class="card"><h1>Set a new password</h1><p class="mut">Replace your temporary password to continue.</p><form onsubmit="chpw(event)">${field('New password (min 8, with a number)','np','password','','minlength=8 required autocomplete=new-password')}${field('Confirm password','cp','password','','required')}<p id="pe" role="alert" class="b bad" hidden></p><button class="btn p" style="margin-top:14px">Save and continue</button></form></div></div>`}
async function chpw(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),p=$('#pe');let m=f.np.length<8||!/\d/.test(f.np)?'Use at least 8 characters including a number.':f.np!=f.cp?'Passwords do not match.':'';
 if(m){p.hidden=false;p.textContent=m;return}ME.pw=await H(f.np);ME.must=0;save();toast('Password updated');render()}
// shell
function shell(body,crumb){const i=ME.role=='instructor',nav=i?[['/','Dashboard'],['/classes','Classrooms'],['/students','Students']]:[['/','Dashboard'],['/progress','My progress'],['/notifs','Notifications'+(DB.notifs.filter(n=>n.u==ME.id&&!n.r).length?' <em class="nb">'+DB.notifs.filter(n=>n.u==ME.id&&!n.r).length+'</em>':'')],['/profile','Profile']];
 const h=location.hash.slice(1)||'/';return`<div class="shell"><nav class="side" aria-label="Main"><div class="brand"><i></i>Classroom</div>${nav.map(([p,l])=>`<a class="nl" href="#${p}" ${h==p?'aria-current="page"':''}>${l}</a>`).join('')}<div style="margin-top:auto" class="row"><button class="btn s" onclick="theme()">Theme</button><button class="btn s" onclick="logout()">Sign out</button></div><small class="mut" style="padding:6px 12px">${E(ME.name)}</small></nav><main id="main"><div class="crumb">${crumb||''}</div>${body}</main></div>`}
const theme=()=>{const d=document.documentElement.dataset.theme=='dark'?'light':'dark';document.documentElement.dataset.theme=d;localStorage.setItem('cm_theme',d)};
const feed=()=>`<ul class="feed">${DB.log.slice(0,8).map(l=>`<li>${E(l.t)} <small class="mut">${fd(l.at)}</small></li>`).join('')||'<li class="empty">No activity yet.</li>'}</ul>`;
// instructor
function iDash(){const cl=DB.classes.filter(c=>!c.arch),sts=new Set(cl.flatMap(c=>c.st)),tog=DB.subs.filter(s=>s.sc==null).length,all=[...sts].map(s=>avg(s,null)),
 sc=DB.subs.filter(s=>s.sc!=null).map(s=>s.sc/DB.assigns.find(a=>a.id==s.aid).max),av=sc.length?Math.round(sc.reduce((a,b)=>a+b)/sc.length*100):0,ap=Math.round(DB.att.filter(a=>a.v!='A').length/(DB.att.length||1)*100);
 const risk=cl.flatMap(c=>c.st.map(s=>({s,c,a:avg(s,c.id),p:attP(s,c.id),m:DB.assigns.filter(x=>x.cid==c.id&&stat(x,s)=='missing').length}))).filter(r=>(r.a!=null&&r.a<60)||r.p<80||r.m);
 return shell(`<h1>Good to see you, ${E(ME.name.split(' ')[1]||ME.name)}</h1><p class="mut">Live overview of your classrooms.</p>
<div class="grid"><div class="card stat"><span class="mut">Active classrooms</span><b>${cl.length}</b></div><div class="card stat"><span class="mut">Students</span><b>${sts.size}</b></div><div class="card stat"><span class="mut">To grade</span><b>${tog}</b></div><div class="card stat"><span class="mut">Average score</span><b>${av}%</b></div></div>
<div class="grid g2" style="margin-top:16px"><div class="card"><h2>Average score by class</h2>${bars(cl.map(c=>{const g=DB.subs.filter(s=>s.sc!=null&&DB.assigns.find(a=>a.id==s.aid).cid==c.id);return[c.code,g.length?Math.round(g.reduce((t,s)=>t+s.sc/DB.assigns.find(a=>a.id==s.aid).max,0)/g.length*100):null]}))}</div>
<div class="card row" style="gap:20px"><div>${ring(ap,'Attendance')}</div><div><h2>Attendance</h2><p class="mut">Present, late and excused across all classes, last 14 days.</p></div></div>
<div class="card"><h2>At-risk students</h2>${risk.length?`<table><tbody>${risk.map(r=>`<tr><td><a href="#/student/${r.s}">${E(U(r.s).name)}</a><br><small class="mut">${r.c.code}</small></td><td>${r.a??'–'}% avg</td><td>${r.p}% att.</td><td>${r.m?`<span class="b bad">${r.m} missing</span>`:''}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">No one is at risk.</p>'}</div>
<div class="card"><h2>Recent activity</h2>${feed()}</div></div>`,'Dashboard')}
function iClasses(){return shell(`<div class="row sp"><h1>Classrooms</h1><button class="btn p" onclick="newClass()">New classroom</button></div><div class="grid">${DB.classes.map(c=>`<div class="card cc" tabindex="0" onclick="location.hash='#/class/${c.id}'" onkeydown="event.key=='Enter'&&(location.hash='#/class/${c.id}')"><h3>${E(c.name)} ${c.arch?'<span class="b n">archived</span>':''}</h3><p class="mut">${c.code} · ${c.st.length} students</p><div class="bar"><i style="width:${Math.round(c.st.reduce((t,s)=>t+comp(s,c.id),0)/(c.st.length||1))}%"></i></div><small class="mut">Avg completion</small></div>`).join('')||'<p class="empty">No classrooms yet. Create your first one.</p>'}</div>`,'Classrooms')}
const newClass=()=>modal('New classroom',field('Name','n','text','','required')+field('Code','c','text','','required'),f=>{DB.classes.push({id:uid(),name:f.n,code:f.c,arch:0,st:[],mods:[]});log('Created classroom '+f.n);save();render();toast('Classroom created')});
function iClass(id){const c=C_(id);if(!c)return iClasses();const A=DB.assigns.filter(a=>a.cid==id),T={roster:'Roster',content:'Content',assign:'Assignments',att:'Attendance',ann:'Announcements'};let b='';
 if(tab=='roster')b=`<div class="row sp"><h2>Roster</h2><button class="btn p" onclick="addStu('${id}')">Add student</button></div><div class="scroll"><table><tr><th>Name</th><th>Email</th><th>Avg</th><th>Attendance</th><th></th></tr>${c.st.map(s=>`<tr><td><a href="#/student/${s}">${E(U(s).name)}</a>${U(s).on?'':' <span class="b n">inactive</span>'}</td><td>${E(U(s).email)}</td><td>${avg(s,id)??'–'}%</td><td>${attP(s,id)??'–'}%</td><td><button class="btn s d" onclick="rmStu('${id}','${s}')">Remove</button></td></tr>`).join('')}</table></div>${c.st.length?'':'<p class="empty">No students yet.</p>'}`;
 if(tab=='content')b=`<div class="row sp"><h2>Modules</h2><button class="btn p" onclick="addMod('${id}')">Add module</button></div>${c.mods.map((m,mi)=>`<div class="card" style="margin-bottom:12px"><div class="row sp"><h3>${E(m.t)}</h3><button class="btn s" onclick="addItem('${id}',${mi})">Add material</button></div>${m.items.map(i=>`<p><a href="${E(i.u)}" target="_blank" rel="noopener">${E(i.t)}</a> <span class="b n">v${i.v}</span> <button class="btn s" onclick="editItem('${id}',${mi},'${m.items.indexOf(i)}')">Update</button></p>`).join('')||'<p class="mut">Empty module.</p>'}</div>`).join('')||'<p class="empty">Add a module to structure your course.</p>'}`;
 if(tab=='assign')b=`<div class="row sp"><h2>Assignments</h2><button class="btn p" onclick="newAssign('${id}')">New assignment</button></div>${A.map(a=>{const cnt=k=>c.st.filter(s=>stat(a,s)==k).length;return`<div class="card" style="margin-bottom:12px"><div class="row sp"><div><h3>${E(a.t)}</h3><small class="mut">Due ${fd(a.due)} · ${a.max} pts</small></div><a class="btn s" href="#/grade/${a.id}">Open board</a></div><div class="row" style="margin-top:8px">${['submitted','late','missing','graded'].map(k=>`<span class="b ${BC[k]}">${cnt(k)} ${k}</span>`).join('')}</div></div>`}).join('')||'<p class="empty">No assignments yet.</p>'}`;
 if(tab=='att')b=attMgr(id);
 if(tab=='ann')b=`<div class="row sp"><h2>Announcements</h2><button class="btn p" onclick="newAnn('${id}')">Post announcement</button></div>${DB.anns.filter(a=>a.cid==id).map(a=>`<div class="card" style="margin-bottom:10px"><p>${E(a.t)}</p><small class="mut">${fd(a.at)}</small></div>`).join('')||'<p class="empty">Nothing posted yet.</p>'}`;
 return shell(`<div class="row sp"><div><h1>${E(c.name)}</h1><p class="mut">${c.code}</p></div><div class="row"><button class="btn" onclick="arch('${id}')">${c.arch?'Unarchive':'Archive'}</button><button class="btn d" onclick="delClass('${id}')">Delete</button></div></div><div class="tabs" role="tablist">${Object.entries(T).map(([k,l])=>`<button role="tab" aria-selected="${tab==k}" onclick="tab='${k}';render()">${l}</button>`).join('')}</div>${b}`,`<a href="#/classes">Classrooms</a> / ${E(c.name)}`)}
function addStu(cid){modal('Add student',field('Full name','n','text','','required')+field('Email','e','email','','required'),async f=>{const em=f.e.trim().toLowerCase();let u=DB.users.find(x=>x.email==em);const c=C_(cid);let p='';
 if(!u){p=tmp();u={id:uid(),role:'student',name:f.n,email:em,pw:await H(p),must:1,on:1};DB.users.push(u)}if(u.role!='student')return toast('That email belongs to an instructor.'),false;if(!c.st.includes(u.id))c.st.push(u.id);log(u.name+' joined '+c.name);save();render();if(p)credM(u,p);else toast('Existing student enrolled')})}
const credM=(u,p)=>{$('#modal').innerHTML=`<div class="dlg" role="dialog" aria-modal="true"><h2>Share these credentials</h2><p>${E(u.name)} must change this password at first sign-in. It is shown only once.</p><p><b>${E(u.email)}</b><br><code>${E(p)}</code></p><button class="btn p" onclick="navigator.clipboard.writeText('${E(u.email)} / ${E(p)}');toast('Copied')">Copy</button> <button class="btn" onclick="closeM()">Done</button></div>`;deco($('#modal'))};
const rmStu=(c,s)=>confirmM('Remove '+U(s).name+' from this classroom?',()=>{C_(c).st=C_(c).st.filter(x=>x!=s);save();render();toast('Student removed')});
const addMod=id=>modal('Add module',field('Title','t','text','','required'),f=>{C_(id).mods.push({t:f.t,items:[]});log('Content updated in '+C_(id).name);save();render()});
const addItem=(id,mi)=>modal('Add material',field('Title','t','text','','required')+field('Link (PDF, video, doc)','u','url','','required')+'<label for="f_b">Description (rich text: use basic HTML-free notes)</label><textarea id="f_b" name="b"></textarea>',f=>{C_(id).mods[mi].items.push({t:f.t,u:f.u,v:1});C_(id).st.forEach(s=>ntf(s,'New material: '+f.t));log('Material added: '+f.t);save();render();toast('Material added')});
const editItem=(id,mi,ii)=>{const i=C_(id).mods[mi].items[ii];modal('Update material',field('Title','t','text',i.t,'required')+field('Link','u','url',i.u,'required'),f=>{i.t=f.t;i.u=f.u;i.v++;C_(id).st.forEach(s=>ntf(s,'Updated: '+i.t));log('Material updated: '+i.t+' (v'+i.v+')');save();render();toast('Updated to v'+i.v)})};
const newAssign=id=>modal('New assignment',field('Title','t','text','','required')+'<label for="f_d">Instructions</label><textarea id="f_d" name="d"></textarea>'+field('Due date','due','date',dstr(now()+7*DAY),'required')+field('Max score','max','number','100','min=1 required'),f=>{DB.assigns.push({id:uid(),cid:id,t:f.t,d:f.d,due:new Date(f.due+'T23:59').getTime(),max:+f.max});C_(id).st.forEach(s=>ntf(s,'New assignment: '+f.t));log('Assignment created: '+f.t);save();render();toast('Assignment created')});
const newAnn=id=>modal('Post announcement','<label for="f_t">Message</label><textarea id="f_t" name="t" required></textarea>',f=>{DB.anns.unshift({id:uid(),cid:id,t:f.t,at:now()});C_(id).st.forEach(s=>ntf(s,'Announcement in '+C_(id).name));log('Announcement posted in '+C_(id).name);save();render();toast('Posted')});
const mark=(c,s,v)=>{const d=dstr(now());DB.att=DB.att.filter(a=>!(a.cid==c&&a.s==s&&a.d==d));if(v)DB.att.push({cid:c,d,s,v});save();render();toast('Attendance saved')};
const arch=id=>{C_(id).arch^=1;save();render();toast('Updated')},delClass=id=>confirmM('Delete this classroom and its assignments? This cannot be undone.',()=>{DB.classes=DB.classes.filter(c=>c.id!=id);DB.assigns=DB.assigns.filter(a=>a.cid!=id);location.hash='#/classes';save();render()});
function iGrade(id){const a=DB.assigns.find(x=>x.id==id);if(!a)return iClasses();const c=C_(a.cid);return shell(`<h1>${E(a.t)}</h1><p class="mut">Due ${fd(a.due)} · ${a.max} pts · updates automatically</p><div class="row" style="margin:10px 0"><button class="btn" onclick="csv('${a.cid}')">Export gradebook CSV</button></div><div class="card scroll"><table><tr><th>Student</th><th>Status</th><th>Score</th><th></th></tr>${c.st.map(s=>{const x=sub(a.id,s),st=stat(a,s);return`<tr><td>${E(U(s).name)}</td><td>${badge(st)}</td><td>${x?.sc??'–'}/${a.max}</td><td>${x?`<button class="btn s" onclick="gradeM('${a.id}','${s}')">${x.sc!=null?'Edit grade':'Grade'}</button>`:''}</td></tr>`}).join('')}</table></div>`,`<a href="#/classes">Classrooms</a> / <a href="#/class/${a.cid}">${E(c.name)}</a> / ${E(a.t)}`)}
const gradeM=(aid,sid)=>{const a=DB.assigns.find(x=>x.id==aid),x=sub(aid,sid);modal('Grade '+U(sid).name,`<p class="card">${E(x.text)}</p>`+field('Score (max '+a.max+')','sc','number',x.sc??'',`min=0 max=${a.max} required`)+'<label for="f_fb">Feedback</label><textarea id="f_fb" name="fb">'+E(x.fb)+'</textarea>',f=>{x.sc=+f.sc;x.fb=f.fb;ntf(sid,'Graded: '+a.t+' ('+x.sc+'/'+a.max+')');log(U(sid).name+' graded on '+a.t);save();render();toast('Grade saved')})};
function csv(cid){const c=C_(cid),A=DB.assigns.filter(a=>a.cid==cid),q=v=>'"'+String(v).replace(/"/g,'""').replace(/^[=+\-@]/,"'$&")+'"',r=[['Student','Email',...A.map(a=>a.t),'Average %'].map(q).join(',')];c.st.forEach(s=>r.push([U(s).name,U(s).email,...A.map(a=>sub(a.id,s)?.sc??''),avg(s,cid)??''].map(q).join(',')));
 const l=document.createElement('a');l.href=URL.createObjectURL(new Blob([r.join('\n')],{type:'text/csv'}));l.download=c.code+'-gradebook.csv';l.click()}
function iStudents(){return shell(`<h1>Students</h1>${DB.resets.length?`<div class="card" style="margin-bottom:12px"><h2>Reset requests</h2>${DB.resets.map(r=>`<div class="row sp"><span>${E(U(r.sid).name)} · ${fd(r.at)}</span><button class="btn s p" onclick="resetPw('${r.sid}')">Issue new password</button></div>`).join('')}</div>`:''}<div class="card scroll"><table><tr><th>Name</th><th>Email</th><th>Classes</th><th></th></tr>${DB.users.filter(u=>u.role=='student').map(u=>`<tr><td><a href="#/student/${u.id}">${E(u.name)}</a> ${u.on?'':'<span class="b n">inactive</span>'}</td><td>${E(u.email)}</td><td>${DB.classes.filter(c=>c.st.includes(u.id)).length}</td><td><button class="btn s" onclick="resetPw('${u.id}')">Reset password</button> <button class="btn s d" onclick="toggleOn('${u.id}')">${u.on?'Deactivate':'Reactivate'}</button></td></tr>`).join('')}</table></div>`,'Students')}
const resetPw=async id=>{const p=tmp(),u=U(id);u.pw=await H(p);u.must=1;DB.resets=DB.resets.filter(r=>r.sid!=id);save();render();credM(u,p)};
const toggleOn=id=>confirmM('Change this student\'s access? Their data is kept.',()=>{U(id).on^=1;save();render()});
function iStudent(id){const u=U(id);if(!u)return iStudents();return shell(`<div class="row sp"><div><h1>${E(u.name)}</h1><p class="mut">${E(u.email)}</p></div><button class="btn s" onclick="editName('${id}')">Update name</button></div><div class="grid g2">${DB.classes.filter(c=>c.st.includes(id)).map(c=>`<div class="card"><h2>${E(c.name)}</h2><div class="row"><div>${ring(comp(id,c.id),'Completion')}<br><small class="mut">Completion</small></div><div><p>Avg score: <b>${avg(id,c.id)??'–'}%</b></p><p>Attendance: <b>${attP(id,c.id)}%</b></p></div></div>${heat(id,c.id)}<table>${DB.assigns.filter(a=>a.cid==c.id).map(a=>{const x=sub(a.id,id);return`<tr><td>${E(a.t)}</td><td>${badge(stat(a,id))}</td><td>${x?.sc??'–'}/${a.max}</td></tr>${x?.fb?`<tr><td colspan=3><small class="mut">Feedback: ${E(x.fb)}</small></td></tr>`:''}`}).join('')}</table></div>`).join('')}</div><div class="card" style="margin-top:16px"><h2>Private notes</h2>${DB.notes.filter(n=>n.sid==id).map(n=>`<p>${E(n.t)} <span class="b ${n.sh?'ok':'n'}">${n.sh?'shared':'private'}</span></p>`).join('')}<button class="btn s" onclick="addNote('${id}')">Add note</button></div>`,`<a href="#/students">Students</a> / ${E(u.name)}`)}
const addNote=id=>modal('Add note','<label for="f_t">Note</label><textarea id="f_t" name="t" required></textarea><label><input type="checkbox" name="sh" style="width:auto"> Share with student</label>',f=>{DB.notes.push({sid:id,t:f.t,sh:!!f.sh});if(f.sh)ntf(id,'New feedback note from your instructor');save();render()});
// student
function sDash(){const cl=mine(),up=DB.assigns.filter(a=>cl.some(c=>c.id==a.cid)&&!sub(a.id,ME.id)).sort((a,b)=>a.due-b.due);return shell(`<h1>Hi, ${E(ME.name.split(' ')[0])}</h1><p class="mut">Your classrooms and what's due next.</p><div class="grid">${cl.map(c=>`<div class="card cc" tabindex="0" onclick="location.hash='#/class/${c.id}'" onkeydown="event.key=='Enter'&&(location.hash='#/class/${c.id}')"><h3>${E(c.name)}</h3><p class="mut">${c.code}</p><div class="row">${ring(comp(ME.id,c.id),'Completion')}<small>Avg ${avg(ME.id,c.id)??'–'}%<br>Attendance ${attP(ME.id,c.id)}%</small></div></div>`).join('')||'<p class="empty">You are not enrolled in any classroom yet.</p>'}</div><div class="card" style="margin-top:16px"><h2>Upcoming deadlines</h2>${up.map(a=>`<div class="row sp"><a href="#/class/${a.cid}">${E(a.t)}</a>${badge(stat(a,ME.id))}<small>${fd(a.due)}</small></div>`).join('')||'<p class="empty">All caught up.</p>'}</div>`,'Dashboard')}
function sClass(id){const c=mine().find(x=>x.id==id);if(!c)return sDash();return shell(`<h1>${E(c.name)}</h1><div class="grid g2"><div class="card"><h2>Assignments</h2>${DB.assigns.filter(a=>a.cid==id).map(a=>{const x=sub(a.id,ME.id);return`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><div class="row sp"><b>${E(a.t)}</b>${badge(stat(a,ME.id))}</div><small class="mut">Due ${fd(a.due)} · ${a.max} pts</small><p>${E(a.d)}</p>${x?.sc!=null?`<p><b>${x.sc}/${a.max}</b> ${E(x.fb)}</p>`:''}${x?'':`<button class="btn s p" onclick="submitM('${a.id}')">Submit work</button>`}</div>`}).join('')}</div><div><div class="card" style="margin-bottom:16px"><h2>Announcements</h2>${DB.anns.filter(a=>a.cid==id).map(a=>`<p>${E(a.t)}<br><small class="mut">${fd(a.at)}</small></p>`).join('')||'<p class="mut">None yet.</p>'}</div><div class="card"><h2>Materials</h2>${c.mods.map(m=>`<h3>${E(m.t)}</h3>${m.items.map(i=>`<p><a href="${E(i.u)}" target="_blank" rel="noopener">${E(i.t)}</a> <span class="b n">v${i.v}</span></p>`).join('')}`).join('')||'<p class="mut">No materials yet.</p>'}</div></div></div>`,`<a href="#/">Dashboard</a> / ${E(c.name)}`)}
const submitM=aid=>{const a=DB.assigns.find(x=>x.id==aid);modal('Submit '+a.t,(now()>a.due?'<p class="b bad">This will be marked late.</p>':'')+'<label for="f_t">Your response</label><textarea id="f_t" name="t" required></textarea><label for="f_f">Attach file (PDF, image, doc; max 5 MB)</label><input id="f_f" name="f" type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx,.txt">',f=>{const fl=$('#f_f').files[0];if(fl&&fl.size>5e6)return toast('File is larger than 5 MB.'),false;DB.subs.push({id:uid(),aid,sid:ME.id,text:f.t+(fl?' [file: '+fl.name+']':''),at:now(),sc:null,fb:''});ntf('i1',ME.name+' submitted '+a.t);log(ME.name+' submitted '+a.t);save();render();toast('Submitted')})};
function sProg(){const cl=mine();return shell(`<h1>My progress</h1><div class="grid g2">${cl.map(c=>`<div class="card"><h2>${E(c.name)}</h2><div class="row"><div>${ring(comp(ME.id,c.id),'Completion')}</div><div style="flex:1"><p>Average score</p><div class="bar"><i style="width:${avg(ME.id,c.id)||0}%"></i></div><p style="margin-top:8px">Attendance</p><div class="bar"><i style="width:${attP(ME.id,c.id)||0}%"></i></div></div></div><p>${heat(ME.id,c.id)}</p>${avg(ME.id,c.id)>=85?'<span class="b ok">High achiever</span>':''} ${attP(ME.id,c.id)>=95?'<span class="b ok">Perfect attendance streak</span>':''}</div>`).join('')}</div>`,'My progress')}
function sNotifs(){const n=DB.notifs.filter(x=>x.u==ME.id);setTimeout(()=>{if(n.some(x=>!x.r)){n.forEach(x=>x.r=1);save();render()}},800);return shell(`<h1>Notifications</h1><div class="card">${n.map(x=>`<p>${x.r?'':'<span class="b n">new</span> '}${E(x.t)} <small class="mut">${fd(x.at)}</small></p>`).join('')||'<p class="empty">No notifications yet.</p>'}</div>`,'Notifications')}
function profile(){return shell(`<h1>Profile</h1><div class="card" style="max-width:480px"><form onsubmit="saveProf(event)">${field('Name','n','text',ME.name,'required')}${field('Email','e','email',ME.email,'disabled')}${field('New password (optional)','np','password','','minlength=8 autocomplete=new-password')}<button class="btn p" style="margin-top:14px">Save changes</button></form></div>`,'Profile')}
const saveProf=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.n&&f.n.trim()!=ME.name){if(ME.role=='student'&&ME.nc&&now()-ME.nc<30*DAY)return toast('You can change your name again after '+fd(ME.nc+30*DAY)+'.');ME.name=f.n.trim();if(ME.role=='student')ME.nc=now()}if(f.np)ME.pw=await H(f.np);save();render();toast('Profile saved')};
// router
function render(){render0();deco($('#app'))}
function render0(){const a=$('#app');if(!ME){a.innerHTML=authView();return}if(ME.must){a.innerHTML=forceView();return}
 const [,p,id]=(location.hash.slice(1)||'/').split('/'),i=ME.role=='instructor';
 a.innerHTML=i?(p==''?iDash():p=='classes'?iClasses():p=='class'?iClass(id):p=='grade'?iGrade(id):p=='students'?iStudents():p=='student'?iStudent(id):iDash()):(p==''?sDash():p=='class'?sClass(id):p=='progress'?sProg():p=='notifs'?sNotifs():p=='profile'?profile():sDash())}
window.addEventListener('hashchange',()=>{tab='roster';render();$('#app').focus()});
window.addEventListener('storage',e=>{if(e.key=='cm_db'&&ME&&!$('#modal').innerHTML){DB=JSON.parse(e.newValue);ME=U(ME.id);render()}});
setInterval(()=>{if(ME&&!$('#modal').innerHTML&&!document.activeElement?.matches('input,select,textarea')){const d=JSON.parse(localStorage.getItem('cm_db')||'null');if(d&&JSON.stringify(d)!=JSON.stringify(DB)){DB=d;ME=U(ME.id);render()}}},5000);
// ===== v2: Indian demo data, dense dashboards, attendance manager, student experience =====
async function seed(){const P=await H('Learn123!'),T=await H('Teach123!'),n=now(),
 N=['Ananya Sharma','Rohan Mehta','Priya Nair','Arjun Patel','Sneha Reddy','Kabir Singh','Meera Iyer','Aditya Rao','Ishita Gupta','Vivaan Joshi'],
 Us=[{id:'i1',role:'instructor',name:'Dr. Maya Rao',email:'instructor@demo.edu',pw:T,must:0,on:1},...N.map((x,i)=>({id:'s'+i,role:'student',name:x,email:x.split(' ')[0].toLowerCase()+'@demo.edu',pw:P,must:0,on:1}))],
 M=(t,u,v=1)=>({t,u,v}),
 C=[{id:'c1',name:'Video Editing Mastery',code:'VE-101',arch:0,st:['s0','s1','s2','s3','s4','s5','s6'],mods:[{t:'Module 1: Cutting and pacing',items:[M('Timeline basics (PDF)','https://example.com/timeline.pdf',2),M('J-cuts and L-cuts (video)','https://example.com/jl')]},{t:'Module 2: Colour and sound',items:[M('LUTs explained','https://example.com/luts')]}]},
 {id:'c2',name:'CAD & 3D Design Fundamentals',code:'CAD-210',arch:0,st:['s0','s1','s3','s4','s7','s8','s9'],mods:[{t:'Module 1: Sketching and constraints',items:[M('Sketch constraints guide (PDF)','https://example.com/sketch.pdf'),M('Intro to parametric modelling','https://example.com/param')]}]},
 {id:'c3',name:'Motion Graphics Studio',code:'MG-150',arch:0,st:['s0','s2','s5','s6','s8','s9'],mods:[{t:'Module 1: Keyframes and easing',items:[M('Easing curves cheat sheet (PDF)','https://example.com/ease.pdf'),M('Logo reveal walkthrough','https://example.com/logo')]}]}],
 D=[['c1','Cut a 60-second travel reel',-6,50],['c1','Colour grading exercise',3,30],['c1','Audio mixing task',9,20],['c2','Sketch a bracket in CAD',-4,40],['c2','Assembly: gearbox model',5,60],['c3','Logo reveal animation',-2,50],['c3','Kinetic typography',6,40]],
 A=D.map(([c,t,d,m],i)=>({id:'a'+i,cid:c,t,d:'Follow the brief shared in class and upload your project file.',due:n+d*DAY,max:m})),S=[],FB=['Strong pacing and clean cuts.','Good work. Check your alignment next time.','Nice effort; refine the details.'];
 A.forEach((a,ai)=>C.find(c=>c.id==a.cid).st.forEach((s,i)=>{const h=(i*7+ai*3)%10;if(a.due>n){if(h<2)S.push({id:uid(),aid:a.id,sid:s,text:'Early submission.',at:n-DAY,sc:null,fb:''})}else if(h<9)S.push({id:uid(),aid:a.id,sid:s,text:'Submitted my project file.',at:h==8?a.due+DAY:a.due-DAY,sc:h<6?Math.round(a.max*(.55+((i*13+ai*5)%40)/100)):null,fb:h<6?FB[(i+ai)%3]:''})}));
 const AT=[];C.forEach((c,ci)=>{for(let d=1;d<=14;d++)c.st.forEach((s,i)=>AT.push({cid:c.id,d:dstr(n-d*DAY),s,v:(d*7+i*3+ci)%11==0?'A':(d*5+i+ci)%9==0?'L':(d*3+i)%13==0?'E':'P'}))});
 return{v:2,users:Us,classes:C,assigns:A,subs:S,att:AT,notes:[],resets:[],
 anns:[{id:uid(),cid:'c1',t:'Bring your footage drive on Friday. We start colour grading.',at:n-DAY},{id:uid(),cid:'c2',t:'Gearbox assembly files are due next week. Ask doubts in Monday class.',at:n-2*DAY},{id:uid(),cid:'c3',t:'Studio session moved to 4 PM on Thursday.',at:n-3*DAY}],
 notifs:[{id:uid(),u:'s0',t:'Graded: Cut a 60-second travel reel',at:n-DAY,r:0},{id:uid(),u:'s0',t:'Announcement in Video Editing Mastery',at:n-DAY,r:0}],
 log:[{t:'Rohan Mehta submitted Cut a 60-second travel reel',at:n-5*DAY},{t:'Priya Nair graded on Logo reveal animation',at:n-2*DAY},{t:'Announcement posted in Motion Graphics Studio',at:n-3*DAY},{t:'Material updated: Timeline basics (PDF) (v2)',at:n-4*DAY},{t:'Kabir Singh submitted Sketch a bracket in CAD',at:n-4*DAY}]}}
const av=n=>`<span class="av" aria-hidden="true">${E(String(n).trim()[0])}</span>`,cn=id=>C_(id)?.name||'',pct=(a,b)=>b?Math.round(a/b*100):0;
const wc=a=>{const st=stat(a,ME.id);return`<a class="card wc ${st=='missing'?'miss':''}" href="#/class/${a.cid}"><span class="wi">${I(st=='graded'?'star':st=='missing'?'alert':st=='pending'?'clock':'check',20)}</span><div class="wb"><b>${E(a.t)}</b><small class="mut">${E(cn(a.cid))} · Due ${fd(a.due)}</small></div>${badge(st)}</a>`};
const ri=(ic,html)=>`<div class="ri"><span class="ric">${I(ic,16)}</span><div class="wb">${html}</div></div>`;
function iDash(){const cl=DB.classes.filter(c=>!c.arch),ids=new Set(cl.map(c=>c.id)),sts=new Set(cl.flatMap(c=>c.st)),A=DB.assigns.filter(a=>ids.has(a.cid)),aid=new Set(A.map(a=>a.id)),
 tog=DB.subs.filter(s=>s.sc==null&&aid.has(s.aid)),g=DB.subs.filter(s=>s.sc!=null&&aid.has(s.aid)),m=s=>DB.assigns.find(a=>a.id==s.aid).max,
 avs=pct(g.reduce((t,s)=>t+s.sc/m(s),0),g.length),rec=DB.att.filter(a=>ids.has(a.cid)),ap=pct(rec.filter(a=>a.v=='P'||a.v=='E').length,rec.length),
 risk=cl.flatMap(c=>c.st.map(s=>({s,c,a:avg(s,c.id),p:attP(s,c.id),m:A.filter(x=>x.cid==c.id&&stat(x,s)=='missing').length}))).filter(r=>(r.a!=null&&r.a<60)||(r.p!=null&&r.p<80)||r.m),
 ng=A.map(a=>({a,n:tog.filter(s=>s.aid==a.id).length})).filter(x=>x.n).slice(0,4),up=A.filter(a=>a.due>now()).sort((a,b)=>a.due-b.due).slice(0,5),
 ai=t=>/graded/.test(t)?'star':/submitted/.test(t)?'send':/nnounce/.test(t)?'megaphone':'file';
 return shell(`<div class="row sp"><div><h1>Good to see you, ${E(ME.name.split(' ').pop())}</h1><p class="mut">Live overview of your classrooms.</p></div></div>
<div class="grid" style="margin-bottom:16px"><div class="card stat"><span class="mut">Active classrooms</span><b>${cl.length}</b></div><div class="card stat"><span class="mut">Students</span><b>${sts.size}</b></div><div class="card stat acc"><span class="mut">Needs grading</span><b>${tog.length}</b></div><div class="card stat"><span class="mut">Average score</span><b>${avs}%</b></div></div>
<div class="dg"><div class="card"><h2>Average score by class</h2>${bars(cl.map(c=>{const x=g.filter(s=>DB.assigns.find(a=>a.id==s.aid).cid==c.id);return[c.code,x.length?pct(x.reduce((t,s)=>t+s.sc/m(s),0),x.length):null]}))}</div>
<div class="card"><h2>Attendance</h2><div class="row" style="gap:16px">${ring(ap,'Attendance')}<p class="mut">Present or excused across all classes. Recalculates when you edit attendance.</p></div></div>
<div class="card"><h2>Needs grading</h2>${ng.map(x=>`<a class="ri lnk" href="#/grade/${x.a.id}"><span class="ric">${I('edit',16)}</span><div class="wb"><b>${E(x.a.t)}</b><small class="mut">${E(C_(x.a.cid).code)}</small></div><span class="b warn">${x.n} to grade</span></a>`).join('')||`<p class="empty">Nothing to grade.</p>`}</div>
<div class="card"><h2>At-risk students</h2>${risk.map(r=>`<div class="ri">${av(U(r.s).name)}<div class="wb"><a href="#/student/${r.s}"><b>${E(U(r.s).name)}</b></a><small class="mut">${E(r.c.code)} · ${r.a??'–'}% avg · ${r.p??'–'}% att.</small></div><span class="b bad">${I('alert',13)}${r.m?r.m+' missing':'At risk'}</span></div>`).join('')||'<p class="empty">No one is at risk.</p>'}</div>
<div class="card"><h2>Upcoming deadlines</h2>${up.map(a=>{const c=C_(a.cid);return`<a class="ri lnk" href="#/grade/${a.id}"><span class="ric">${I('calendar',16)}</span><div class="wb"><b>${E(a.t)}</b><small class="mut">${E(c.code)} · Due ${fd(a.due)}</small></div><small>${DB.subs.filter(s=>s.aid==a.id).length}/${c.st.length}</small></a>`}).join('')||'<p class="empty">No upcoming deadlines.</p>'}</div>
<div class="card"><h2>Recent activity</h2>${DB.log.slice(0,6).map(l=>ri(ai(l.t),`${E(l.t)} <small class="mut">${fd(l.at)}</small>`)).join('')||'<p class="empty">No activity yet.</p>'}</div></div>`,'Dashboard')}
let attD=dstr(now());const AS=[['P','Present'],['L','Late'],['A','Absent'],['E','Excused']];
function attMgr(id){const c=C_(id),T=dstr(now());if(attD>T)attD=T;const day=Object.fromEntries(DB.att.filter(a=>a.cid==id&&a.d==attD).map(a=>[a.s,a.v])),cnt=k=>c.st.filter(s=>day[s]==k).length,rec=DB.att.filter(a=>a.cid==id),
 days=[...Array(14)].map((_,i)=>dstr(now()-(13-i)*DAY));
 return`<div class="dg"><div class="card"><h2>Class attendance</h2><div class="row" style="gap:16px">${ring(pct(rec.filter(a=>a.v=='P'||a.v=='E').length,rec.length),'Class attendance')}<small class="mut">Updates as you edit.</small></div></div>
<div class="card span2"><h2>Last 14 days <small class="mut">Select a day to edit</small></h2><div class="hm">${days.map(d=>{const r=rec.filter(x=>x.d==d),p=r.length?r.filter(x=>x.v=='P'||x.v=='E').length/r.length:null;return`<button class="hc" aria-label="${d}: ${p==null?'not marked':Math.round(p*100)+'% present'}" aria-pressed="${d==attD}" style="background:${p==null?'var(--line2)':`color-mix(in srgb,var(--ok) ${Math.round(25+p*75)}%,var(--card))`}" onclick="attD='${d}';render()">${d.slice(8)}</button>`}).join('')}</div></div>
<div class="card span3"><div class="row sp"><div class="row"><label for="ad" style="margin:0">Date</label><input id="ad" type="date" value="${attD}" max="${T}" style="width:auto" onchange="attD=this.value||attD;render()"><button class="btn s" onclick="attD='${T}';render()">Today</button></div><button class="btn s" onclick="markAll('${id}')">Mark all present</button></div>
<div class="row" style="margin:12px 0">${AS.map(([v,l])=>`<span class="b ${{P:'ok',L:'warn',A:'bad',E:'n'}[v]}">${cnt(v)} ${l.toLowerCase()}</span>`).join('')}<span class="b n">${c.st.filter(s=>!day[s]).length} unmarked</span></div>
<div class="scroll"><table><tr><th>Student</th><th>Status on ${attD}</th><th>Overall</th></tr>${c.st.map(s=>`<tr><td><div class="row" style="gap:10px">${av(U(s).name)}${E(U(s).name)}</div></td><td><div class="seg" role="group" aria-label="Status for ${E(U(s).name)}">${AS.map(([v,l])=>`<button data-v="${v}" aria-pressed="${day[s]==v}" onclick="setAtt('${id}','${s}','${v}')">${l}</button>`).join('')}</div></td><td>${attP(s,id)??'–'}%</td></tr>`).join('')}</table></div></div></div>`}
const setAtt=(c,s,v)=>{const cur=DB.att.find(a=>a.cid==c&&a.s==s&&a.d==attD);DB.att=DB.att.filter(a=>a!==cur);if(!cur||cur.v!=v)DB.att.push({cid:c,d:attD,s,v});save();render();toast('Attendance saved')};
const markAll=c=>{DB.att=DB.att.filter(a=>!(a.cid==c&&a.d==attD));C_(c).st.forEach(s=>DB.att.push({cid:c,d:attD,s,v:'P'}));log('Attendance marked for '+C_(c).name);save();render();toast('Everyone marked present')};
const editName=id=>modal('Update student name',field('Full name','n','text',U(id).name,'required'),f=>{U(id).name=f.n.trim();log('Name updated: '+U(id).name);save();render();toast('Name updated')});
function sDash(){const cl=mine(),ids=cl.map(c=>c.id),A=DB.assigns.filter(a=>ids.includes(a.cid)),todo=A.filter(a=>!sub(a.id,ME.id)),miss=todo.filter(a=>now()>a.due).sort((a,b)=>a.due-b.due),up=todo.filter(a=>now()<=a.due).sort((a,b)=>a.due-b.due),
 oc=pct(A.length-todo.length,A.length),nx=miss[0]||up[0],an=DB.anns.filter(a=>ids.includes(a.cid)).slice(0,4),fb=DB.subs.filter(s=>s.sid==ME.id&&s.fb).sort((a,b)=>b.at-a.at)[0],fa=fb&&DB.assigns.find(a=>a.id==fb.aid);
 return shell(`<h1>Hi, ${E(ME.name.split(' ')[0])}</h1><p class="mut">Pick up where you left off.</p>
<div class="hero"><div class="card"><h2>Continue learning</h2>${nx?`<div class="ri" style="border:0"><span class="wi">${I(miss[0]?'alert':'clock',20)}</span><div class="wb"><b>${E(nx.t)}</b><small class="mut">${E(cn(nx.cid))} · Due ${fd(nx.due)}</small></div></div><a class="btn p" href="#/class/${nx.cid}" style="margin-top:12px">${I('send',18)}Start work</a>`:`<p class="empty">You are all caught up. Nice work.</p>`}</div>
<div class="card row" style="gap:16px">${ring(oc,'Overall completion')}<div><h2 style="margin:0">Overall completion</h2><small class="mut">${A.length-todo.length} of ${A.length} assignments submitted</small></div></div></div>
${miss.length?`<h2 class="sec bad">${I('alert',20)} Missing <span class="b bad">${miss.length}</span></h2><div class="wg">${miss.map(wc).join('')}</div>`:''}
<h2 class="sec">${I('clock',20)} Upcoming</h2><div class="wg">${up.map(wc).join('')||'<p class="empty">Nothing due soon.</p>'}</div>
<div class="dg" style="margin-top:24px"><div class="card"><h2>Recent announcements</h2>${an.map(a=>ri('megaphone',`<b>${E(cn(a.cid))}</b><br>${E(a.t)} <small class="mut">${fd(a.at)}</small>`)).join('')||'<p class="empty">No announcements.</p>'}</div>
<div class="card"><h2>Latest feedback</h2>${fb?`<p><b>${E(fa.t)}</b> <span class="b ok">${fb.sc}/${fa.max}</span></p><p class="fb">${I('edit',15)} ${E(fb.fb)}</p>`:'<p class="empty">Feedback appears here once graded.</p>'}</div>
<div class="card"><h2>Classwork and materials</h2>${cl.flatMap(c=>c.mods.flatMap(m=>m.items.map(i=>ri('file',`<a href="${E(i.u)}" target="_blank" rel="noopener">${E(i.t)}</a><br><small class="mut">${E(c.code)} · ${E(m.t)}</small>`)))).slice(0,6).join('')||'<p class="empty">No materials shared yet.</p>'}</div></div>
<h2 class="sec" style="margin-top:24px">${I('book',20)} My classrooms</h2><div class="grid">${cl.map(c=>`<div class="card cc" tabindex="0" onclick="location.hash='#/class/${c.id}'" onkeydown="event.key=='Enter'&&(location.hash='#/class/${c.id}')"><h3>${E(c.name)}</h3><p class="mut">${c.code}</p><div class="row">${ring(comp(ME.id,c.id),'Completion')}<small>Avg ${avg(ME.id,c.id)??'–'}%<br>Attendance ${attP(ME.id,c.id)??'–'}%</small></div></div>`).join('')||'<p class="empty">You are not enrolled in any classroom yet.</p>'}</div>`,'Dashboard')}
function sProg(){const cl=mine(),ids=cl.map(c=>c.id),A=DB.assigns.filter(a=>ids.includes(a.cid)),oc=pct(A.filter(a=>sub(a.id,ME.id)).length,A.length);
 return shell(`<div class="row sp"><div><h1>My progress</h1><p class="mut">Overall completion across ${cl.length} classes</p></div>${ring(oc,'Overall completion')}</div><div class="dg">${cl.map(c=>{const a=avg(ME.id,c.id),p=attP(ME.id,c.id),cp=comp(ME.id,c.id),f=DB.subs.filter(s=>s.sid==ME.id&&s.fb&&DB.assigns.find(x=>x.id==s.aid).cid==c.id).sort((x,y)=>y.at-x.at)[0],h=DB.att.filter(x=>x.s==ME.id&&x.cid==c.id).sort((x,y)=>x.d<y.d?1:-1).slice(0,10);
 return`<div class="card"><h2>${E(c.name)}</h2><div class="row" style="gap:16px"><div class="tc">${ring(a||0,'Average score')}<small class="mut">Score</small></div><div class="tc">${ring(cp,'Completion')}<small class="mut">Complete</small></div></div><p style="margin:12px 0 6px">Attendance <b>${p??'–'}%</b></p><div class="bar"><i style="width:${p||0}%"></i></div><div style="margin:12px 0">${heat(ME.id,c.id)}</div>
<div class="row">${a>=85?'<span class="b ok">High achiever</span>':''}${p>=95?'<span class="b ok">Great attendance</span>':''}${cp==100?'<span class="b ok">All submitted</span>':''}</div>${f?`<p class="fb">${I('edit',15)} ${E(f.fb)}</p>`:''}
<details><summary>Attendance history (read-only)</summary>${h.map(x=>`<div class="ri"><div class="wb">${x.d}</div>${badge({P:'present',A:'absent',L:'late',E:'excused'}[x.v])}</div>`).join('')||'<p class="mut">No records yet.</p>'}</details></div>`}).join('')}</div>`,'My progress')}
function profile(){const lock=ME.role=='student'&&ME.nc&&now()-ME.nc<30*DAY;return shell(`<h1>Profile</h1><div class="card" style="max-width:520px"><form onsubmit="saveProf(event)">${field('Display name','n','text',ME.name,'required'+(lock?' disabled':''))}${ME.role=='student'?`<p class="mut"><small>${lock?'You can change your name again after '+fd(ME.nc+30*DAY)+'.':'You can change your name once every 30 days.'}</small></p>`:''}${field('Email','e','email',ME.email,'disabled')}${field('New password (optional)','np','password','','minlength=8 autocomplete=new-password')}<button class="btn p" style="margin-top:16px">Save changes</button></form></div>`,'Profile')}
(async()=>{document.documentElement.dataset.theme=localStorage.getItem('cm_theme')||'light';DB=JSON.parse(localStorage.getItem('cm_db')||'null');if(!DB||DB.v!=2){DB=await seed();save()}ME=U(sessionStorage.getItem('cm_me'))||null;render()})();
